name: UPO_TFM
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.2.14
  - anyio=4.9.0
  - argcomplete=3.6.2
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - binutils_impl_linux-64=2.44
  - bioconductor-annotationdbi=1.64.1
  - bioconductor-annotationhub=3.10.0
  - bioconductor-biobase=2.62.0
  - bioconductor-biocbaseutils=1.4.0
  - bioconductor-biocfilecache=2.10.1
  - bioconductor-biocgenerics=0.48.1
  - bioconductor-biocio=1.12.0
  - bioconductor-biocparallel=1.36.0
  - bioconductor-biocversion=3.18.1
  - bioconductor-biostrings=2.70.1
  - bioconductor-data-packages=20250625
  - bioconductor-delayedarray=0.28.0
  - bioconductor-genomeinfodb=1.38.1
  - bioconductor-genomeinfodbdata=1.2.11
  - bioconductor-genomicalignments=1.38.0
  - bioconductor-genomicranges=1.54.1
  - bioconductor-hipathia=3.2.0
  - bioconductor-interactivedisplaybase=1.40.0
  - bioconductor-iranges=2.36.0
  - bioconductor-keggrest=1.42.0
  - bioconductor-limma=3.58.1
  - bioconductor-matrixgenerics=1.14.0
  - bioconductor-multiassayexperiment=1.28.0
  - bioconductor-preprocesscore=1.64.0
  - bioconductor-recount3=1.12.0
  - bioconductor-rhtslib=2.4.0
  - bioconductor-rsamtools=2.18.0
  - bioconductor-rtracklayer=1.62.0
  - bioconductor-s4arrays=1.2.0
  - bioconductor-s4vectors=0.40.2
  - bioconductor-sparsearray=1.2.2
  - bioconductor-summarizedexperiment=1.32.0
  - bioconductor-xvector=0.42.0
  - bioconductor-zlibbioc=1.48.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - comm=0.2.3
  - contourpy=1.3.2
  - curl=8.14.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - debugpy=1.8.15
  - decorator=5.2.1
  - defusedxml=0.7.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gcc_impl_linux-64=15.1.0
  - gfortran_impl_linux-64=15.1.0
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gsl=2.7
  - gxx_impl_linux-64=15.1.0
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=11.3.2
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=8.37.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jq=1.8.1
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.0
  - jupyter-lsp=2.2.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lark=1.2.2
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=20.1.8
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.5
  - libsanitizer=15.1.0
  - libsodium=1.0.20
  - libsqlite=3.50.3
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - make=4.4.1
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlopt=2.9.0
  - notebook-shim=0.2.4
  - numpy=2.2.6
  - oniguruma=6.9.10
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.1
  - pandoc=3.7.0.2
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.1.1
  - pixman=0.46.4
  - platformdirs=4.3.8
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - qhull=2020.2
  - qt6-main=6.9.1
  - r-abind=1.4_5
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-bh=1.87.0_1
  - r-biocmanager=1.30.26
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-bitops=1.0_9
  - r-blob=1.2.4
  - r-boot=1.3_31
  - r-broom=1.0.8
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-car=3.1_3
  - r-cardata=3.0_5
  - r-caret=6.0_94
  - r-cellranger=1.1.0
  - r-class=7.3_23
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-clock=0.7.3
  - r-codetools=0.2_20
  - r-coin=1.4_3
  - r-colorspace=2.1_1
  - r-commonmark=2.0.0
  - r-conflicted=1.2.0
  - r-conquer=1.3.3
  - r-corrplot=0.95
  - r-cowplot=1.2.0
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-crosstalk=1.2.1
  - r-curl=6.2.2
  - r-data.table=1.17.6
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-deriv=4.2.0
  - r-diagram=1.6.5
  - r-digest=0.6.37
  - r-doby=4.7.0
  - r-dplyr=1.1.4
  - r-dt=0.33
  - r-dtplyr=1.3.1
  - r-e1071=1.7_16
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.4
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-filelock=1.0.3
  - r-fontawesome=0.5.3
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-formatr=1.14
  - r-formula=1.2_5
  - r-fs=1.6.6
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.58.0
  - r-future.apply=1.20.0
  - r-gargle=1.5.2
  - r-gbrd=0.4.12
  - r-generics=0.1.4
  - r-ggplot2=3.5.2
  - r-ggpubr=0.6.1
  - r-ggrepel=0.9.6
  - r-ggsci=3.2.0
  - r-ggsignif=0.6.4
  - r-globals=0.18.0
  - r-glue=1.8.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gower=1.0.1
  - r-gridextra=2.3
  - r-gtable=0.3.6
  - r-hardhat=1.4.1
  - r-haven=2.5.4
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.15
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-igraph=2.0.3
  - r-ipred=0.9_15
  - r-irdisplay=1.1
  - r-irkernel=1.3.2
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-kernsmooth=2.23_26
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-lambda.r=1.2.4
  - r-later=1.4.2
  - r-lattice=0.22_7
  - r-lava=1.8.1
  - r-lazyeval=0.2.2
  - r-libcoin=1.0_10
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-lme4=1.1_37
  - r-lubridate=1.9.4
  - r-magrittr=2.0.3
  - r-mass=7.3_60.0.1
  - r-matrix=1.6_5
  - r-matrixmodels=0.5_4
  - r-matrixstats=1.5.0
  - r-memoise=2.0.1
  - r-metbrewer=0.2.0
  - r-mgcv=1.9_3
  - r-microbenchmark=1.5.0
  - r-mime=0.13
  - r-minqa=1.2.8
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-modeltools=0.2_24
  - r-multcomp=1.4_28
  - r-munsell=0.5.1
  - r-mvtnorm=1.3_3
  - r-nlme=3.1_168
  - r-nloptr=2.2.1
  - r-nnet=7.3_20
  - r-numderiv=2016.8_1.1
  - r-openssl=2.3.3
  - r-parallelly=1.45.0
  - r-pbdzmq=0.3_14
  - r-pbkrtest=0.5.5
  - r-pillar=1.11.0
  - r-pkgconfig=2.0.3
  - r-plogr=0.2.0
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-polynom=1.4_1
  - r-prettyunits=1.2.0
  - r-proc=1.18.5
  - r-processx=3.8.6
  - r-prodlim=2025.04.28
  - r-progress=1.2.3
  - r-progressr=0.15.1
  - r-promises=1.3.2
  - r-proxy=0.4_27
  - r-ps=1.9.1
  - r-purrr=1.1.0
  - r-quantreg=6.1
  - r-r.methodss3=1.8.2
  - r-r.oo=1.27.1
  - r-r.utils=2.13.0
  - r-r6=2.6.1
  - r-ragg=1.4.0
  - r-rappdirs=0.3.3
  - r-rbibutils=2.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.1.0
  - r-rcpparmadillo=14.4.2_1
  - r-rcppeigen=0.3.4.0.2
  - r-rcurl=1.98_1.16
  - r-rdpack=2.6.4
  - r-readr=2.1.5
  - r-readxl=1.4.5
  - r-recipes=1.3.1
  - r-reformulas=0.4.1
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-repr=1.1.7
  - r-reprex=2.1.1
  - r-reshape2=1.4.4
  - r-restfulr=0.0.15
  - r-rjson=0.2.23
  - r-rlang=1.1.6
  - r-rmarkdown=2.29
  - r-rpart=4.1.24
  - r-rsqlite=2.4.2
  - r-rstatix=0.7.2
  - r-rstudioapi=0.17.1
  - r-rvest=1.0.4
  - r-sandwich=3.1_1
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-selectr=0.4_2
  - r-servr=0.32
  - r-sessioninfo=1.2.3
  - r-shape=1.4.6.1
  - r-shiny=1.11.1
  - r-snow=0.4_4
  - r-sourcetools=0.1.7_1
  - r-sparsem=1.84_2
  - r-sparsevctrs=0.3.4
  - r-squarem=2021.1
  - r-statmod=1.5.0
  - r-stringi=1.8.7
  - r-stringr=1.5.1
  - r-survival=3.8_3
  - r-sys=3.4.3
  - r-systemfonts=1.2.3
  - r-textshaping=1.0.1
  - r-th.data=1.1_3
  - r-tibble=3.3.0
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-timedate=4041.110
  - r-tinytex=0.57
  - r-tzdb=0.5.0
  - r-utf8=1.2.6
  - r-uuid=1.2_1
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-visnetwork=2.1.2
  - r-vroom=1.6.5
  - r-withr=3.0.2
  - r-xfun=0.52
  - r-xml=3.99_0.17
  - r-xml2=1.3.8
  - r-xtable=1.8_4
  - r-yaml=2.3.10
  - r-zoo=1.8_14
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.26.0
  - rpy2=3.5.11
  - scikit-learn=1.7.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sed=4.9
  - send2trash=1.8.3
  - setuptools=80.9.0
  - simplegeneric=0.8.1
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.7
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - sysroot_linux-64=2.34
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.3
  - tornado=6.5.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250708
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - typing_utils=0.1.0
  - tzdata=2025b
  - tzlocal=5.3
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wayland=1.24.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xmltodict=0.14.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - yq=3.4.3
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
prefix: /home/ags/miniconda3/envs/UPO_TFM
