name: UPO_TFM
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base64enc=0.1_3
  - r-lava=1.8.1
  - r-readr=2.1.5
  - jupyterlab_pygments=0.3.0
  - ipython=8.37.0
  - libtiff==4.7.1
  - pthread-stubs=0.4
  - r-numderiv=2016.8_1.1
  - libopengl=1.7.0
  - libpciaccess=0.18
  - r-sessioninfo=1.2.3
  - libstdcxx-ng==15.2.0
  - r-irkernel=1.3.2
  - r-igraph==2.1.4
  - r-repr=1.1.7
  - r-xtable=1.8_4
  - qhull=2020.2
  - openssl==3.6.0
  - prometheus_client==0.23.1
  - r-fs=1.6.6
  - r-broom==1.0.9
  - brotli-bin==1.2.0
  - r-bit=4.6.0
  - r-forcats=1.0.0
  - bioconductor-zlibbioc=1.48.0
  - toml=0.10.2
  - icu=75.1
  - r-microbenchmark=1.5.0
  - jupyter_client==8.7.0
  - xorg-libxi=1.8.2
  - readline==8.3
  - r-gridextra=2.3
  - r-sass=0.4.10
  - libgfortran-ng==15.2.0
  - parso==0.8.5
  - libxkbcommon==1.11.0
  - charset-normalizer==3.4.4
  - jupyter_events=0.12.0
  - r-biocmanager=1.30.26
  - r-visnetwork==2.1.4
  - r-base=4.3.3
  - keyutils==1.6.3
  - r-future.apply=1.20.0
  - r-munsell=0.5.1
  - libclang-cpp20.1=20.1.8
  - pandocfilters=1.5.0
  - r-boot==1.3_32
  - r-snow=0.4_4
  - cffi==2.0.0
  - binutils_impl_linux-64==2.45
  - httpx=0.28.1
  - krb5=1.21.3
  - pillow==12.1.0
  - r-rstudioapi=0.17.1
  - r-proxy=0.4_27
  - nest-asyncio=1.6.0
  - r-ggsignif=0.6.4
  - ptyprocess=0.7.0
  - r-statmod=1.5.0
  - r-callr=3.7.6
  - seaborn=0.13.2
  - r-googlesheets4==1.1.2
  - numpy=2.2.6
  - glpk=5.0
  - libwebp-base=1.6.0
  - r-conflicted=1.2.0
  - r-ragg==1.5.0
  - r-highr=0.11
  - r-purrr=1.1.0
  - r-systemfonts=1.2.3
  - r-xml=3.99_0.17
  - pickleshare=0.7.5
  - r-sparsevctrs=0.3.4
  - bioconductor-data-packages=20250625
  - pixman=0.46.4
  - r-pkgconfig=2.0.3
  - r-th.data==1.1_4
  - r-dplyr=1.1.4
  - libev=4.33
  - defusedxml=0.7.1
  - r-iterators=1.0.14
  - r-tinytex=0.57
  - bioconductor-limma=3.58.1
  - r-rvest==1.0.5
  - websocket-client==1.9.0
  - r-rappdirs=0.3.3
  - r-magrittr=2.0.3
  - statsmodels==0.14.6
  - fonts-conda-ecosystem=1
  - r-fontawesome=0.5.3
  - jupyterlab_server==2.28.0
  - r-processx=3.8.6
  - attrs==25.4.0
  - bzip2=1.0.8
  - liblzma=5.8.1
  - r-readxl=1.4.5
  - libgfortran5==15.2.0
  - libclang13==21.1.0
  - r-backports=1.5.0
  - r-doby=4.7.0
  - r-coin=1.4_3
  - nbformat=5.10.4
  - bioconductor-multiassayexperiment=1.28.0
  - zstd=1.5.7
  - libuv=1.51.0
  - xcb-util-wm=0.4.2
  - asttokens==3.0.1
  - bioconductor-summarizedexperiment=1.32.0
  - r-bslib=0.9.0
  - wayland=1.24.0
  - r-labeling=0.4.3
  - r-rematch=2.0.0
  - libcurl==8.17.0
  - libexpat==2.7.3
  - libpng==1.6.53
  - r-timechange=0.3.0
  - argon2-cffi-bindings==25.1.0
  - r-timedate=4041.110
  - libzlib=1.3.1
  - pyparsing==3.3.1
  - babel=2.17.0
  - r-generics=0.1.4
  - xorg-libxcursor=1.2.3
  - r-later==1.4.4
  - r-cpp11=0.5.2
  - tomlkit=0.13.3
  - alsa-lib==1.2.15.1
  - r-googledrive==2.1.2
  - r-cowplot=1.2.0
  - json5==0.13.0
  - r-data.table==1.17.8
  - r-matrix=1.6_5
  - r-sourcetools=0.1.7_1
  - seaborn-base=0.13.2
  - cached-property=1.5.2
  - r-r.oo=1.27.1
  - r-colorspace=2.1_1
  - platformdirs==4.5.1
  - pysocks=1.7.1
  - graphite2=1.3.14
  - gsl=2.7
  - libllvm20=20.1.8
  - pygments=2.19.2
  - tk=8.6.13
  - rpds-py==0.30.0
  - gxx_impl_linux-64==15.2.0
  - r-dbplyr==2.5.1
  - r-dt==0.34.0
  - r-xml2==1.4.0
  - libnghttp2==1.67.0
  - r-assertthat=0.2.1
  - r-dbi=1.2.3
  - libsanitizer==15.2.0
  - r-scales=1.4.0
  - tzlocal=5.3
  - r-ggrepel=0.9.6
  - r-ggplot2=3.5.2
  - libbrotlidec==1.2.0
  - r-shape=1.4.6.1
  - pcre2==10.46
  - bioconductor-rhtslib=2.4.0
  - r-zoo=1.8_14
  - gcc_impl_linux-64==15.2.0
  - pandoc==3.8.3
  - r-htmlwidgets=1.6.4
  - cycler=0.12.1
  - debugpy==1.8.19
  - bleach==6.3.0
  - jedi=0.19.2
  - jupyter-lsp==2.3.0
  - r-textshaping==1.0.3
  - libstdcxx-devel_linux-64==15.2.0
  - prompt-toolkit==3.0.52
  - bioconductor-biobase=2.62.0
  - c-ares==1.34.6
  - r-tzdb=0.5.0
  - libbrotlicommon==1.2.0
  - lcms2=2.17
  - fribidi==1.0.16
  - xkeyboard-config==2.46
  - font-ttf-dejavu-sans-mono=2.37
  - r-rcpparmadillo==15.0.2_1
  - python_abi=3.10
  - markupsafe==3.0.3
  - r-r.utils=2.13.0
  - r-prettyunits=1.2.0
  - zeromq=4.3.5
  - r-deriv=4.2.0
  - r-rcolorbrewer=1.1_3
  - r-rstatix=0.7.2
  - r-squarem=2021.1
  - r-blob=1.2.4
  - libbrotlienc==1.2.0
  - libsodium=1.0.20
  - r-multcomp=1.4_28
  - referencing==0.37.0
  - beautifulsoup4==4.14.3
  - r-rjson=0.2.23
  - bioconductor-biocio=1.12.0
  - typing_utils=0.1.0
  - r-modelr=0.1.11
  - executing==2.2.1
  - libglvnd=1.7.0
  - xorg-libsm=1.2.6
  - h2==4.3.0
  - r-ellipsis=0.3.2
  - libdeflate==1.25
  - r-shiny=1.11.1
  - r-class=7.3_23
  - freetype==2.14.1
  - anyio==4.12.0
  - python-dateutil=2.9.0.post0
  - r-digest=0.6.37
  - r-rlang=1.1.6
  - libglib==2.86.2
  - pycparser=2.22
  - bioconductor-genomeinfodb=1.38.1
  - double-conversion=3.3.1
  - r-utf8=1.2.6
  - pip==25.3
  - tzdata==2025c
  - r-lattice=0.22_7
  - packaging=25.0
  - r-vroom=1.6.5
  - zipp=3.23.0
  - nbclient==0.10.4
  - brotli-python==1.2.0
  - r-prodlim=2025.04.28
  - libiconv=1.18
  - bioconductor-annotationhub=3.10.0
  - r-gower=1.0.1
  - harfbuzz==12.2.0
  - r-sparsem=1.84_2
  - r-commonmark=2.0.0
  - nlopt==2.10.0
  - r-httpuv==1.6.16
  - comm=0.2.3
  - jq=1.8.1
  - r-irdisplay=1.1
  - exceptiongroup==1.3.1
  - r-bh=1.87.0_1
  - bioconductor-xvector=0.42.0
  - r-reprex=2.1.1
  - r-sandwich=3.1_1
  - libgcc==15.2.0
  - xcb-util-keysyms=0.4.1
  - libcblas==3.11.0
  - bioconductor-biocbaseutils=1.4.0
  - r-hms=1.1.3
  - r-jquerylib=0.1.4
  - bioconductor-biocfilecache=2.10.1
  - pyzmq==27.1.0
  - tinycss2==1.5.1
  - r-ggpubr=0.6.1
  - libsqlite==3.51.1
  - r-rdpack=2.6.4
  - jsonschema==4.25.1
  - simplegeneric=0.8.1
  - argcomplete==3.6.3
  - pexpect=4.9.0
  - scikit-learn==1.7.2
  - certifi==2025.11.12
  - lark==1.3.1
  - yq=3.4.3
  - r-rcppeigen=0.3.4.0.2
  - r-knitr=1.50
  - libedit=3.1.20250104
  - rfc3986-validator=0.1.1
  - bioconductor-genomeinfodbdata=1.2.11
  - r-gbrd=0.4.12
  - fonttools==4.61.1
  - r-reshape2=1.4.4
  - libxcb=1.17.0
  - overrides=7.7.0
  - xorg-libxtst=1.2.5
  - r-tidyselect=1.2.1
  - r-e1071=1.7_16
  - arrow==1.4.0
  - matplotlib-inline==0.2.1
  - bioconductor-rtracklayer=1.62.0
  - terminado=0.18.1
  - r-glue=1.8.0
  - r-abind=1.4_5
  - python-tzdata==2025.3
  - xorg-libxau=1.0.12
  - r-gargle==1.6.0
  - r-clock=0.7.3
  - cyrus-sasl=2.1.28
  - r-mass=7.3_60.0.1
  - r-clipr=0.8.0
  - ncurses=6.5
  - send2trash==2.0.0
  - brotli==1.2.0
  - r-libcoin=1.0_10
  - r-evaluate==1.0.5
  - bioconductor-genomicranges=1.54.1
  - argon2-cffi=25.1.0
  - ld_impl_linux-64==2.45
  - r-r6=2.6.1
  - sysroot_linux-64==2.39
  - bioconductor-recount3=1.12.0
  - bioconductor-iranges=2.36.0
  - pandas==2.3.3
  - r-sys=3.4.3
  - bioconductor-rsamtools=2.18.0
  - r-tidyverse=2.0.0
  - xorg-libxdmcp=1.1.5
  - bioconductor-genomicalignments=1.38.0
  - ipykernel==7.1.0
  - r-vctrs=0.6.5
  - libssh2=1.11.1
  - xorg-libxt=1.3.1
  - libnsl=2.0.1
  - r-r.methodss3=1.8.2
  - python-json-logger=2.0.7
  - bioconductor-sparsearray=1.2.2
  - fqdn=1.5.1
  - xcb-util-renderutil=0.3.10
  - isoduration=20.11.0
  - r-corrplot=0.95
  - r-lme4=1.1_37
  - wheel=0.45.1
  - python-fastjsonschema==2.21.2
  - scipy=1.15.2
  - r-tidyr=1.3.1
  - urllib3==2.6.2
  - libgomp==15.2.0
  - r-diagram=1.6.5
  - bioconductor-biocversion=3.18.1
  - xcb-util-cursor==0.1.6
  - yaml=0.2.5
  - r-pillar=1.11.0
  - tornado==6.5.4
  - r-promises==1.3.3
  - tktable=2.10
  - pure_eval=0.2.3
  - rpy2=3.5.11
  - setuptools=80.9.0
  - importlib-metadata=8.7.0
  - r-askpass=1.2.1
  - python=3.10.18
  - kiwisolver==1.4.9
  - r-rpart=4.1.24
  - jupyter_server==2.17.0
  - libdrm=2.4.125
  - r-xfun==0.53
  - r-kernsmooth=2.23_26
  - r-formatr=1.14
  - r-modelmetrics=1.2.2.2
  - r-isoband=0.2.7
  - xorg-libice=1.1.2
  - libfreetype==2.14.1
  - r-nlme=3.1_168
  - webcolors==25.10.0
  - r-png=0.1_8
  - matplotlib-base==3.10.8
  - bioconductor-biocgenerics=0.48.1
  - dbus=1.16.2
  - jsonschema-with-format-nongpl==4.25.1
  - bwidget=1.10.1
  - r-filelock=1.0.3
  - xorg-libxfixes==6.0.2
  - r-lambda.r=1.2.4
  - bioconductor-annotationdbi=1.64.1
  - libxml2==2.13.9
  - r-lazyeval=0.2.2
  - r-codetools=0.2_20
  - xorg-libx11=1.8.12
  - ca-certificates==2025.11.12
  - rfc3987-syntax=1.1.0
  - r-rbibutils=2.3
  - oniguruma=6.9.10
  - r-selectr=0.4_2
  - r-ggsci=3.2.0
  - xorg-libxcomposite=0.4.6
  - uri-template=1.3.0
  - r-restfulr=0.0.15
  - xmltodict==1.0.2
  - jupyter_core==5.9.1
  - r-plyr=1.8.9
  - r-ids=1.0.1
  - r-modeltools=0.2_24
  - traitlets=5.14.3
  - r-lifecycle=1.0.4
  - qt6-main==6.9.2
  - libblas==3.11.0
  - r-matrixmodels=0.5_4
  - r-httr=1.4.7
  - font-ttf-inconsolata=3.000
  - pytz=2025.2
  - xorg-libxdamage=1.1.6
  - libcups=2.3.3
  - bioconductor-biostrings=2.70.1
  - r-htmltools=0.5.8.1
  - liblapack==3.11.0
  - types-python-dateutil==2.9.0.20251115
  - r-stringi=1.8.7
  - httpcore=1.0.9
  - r-hardhat==1.4.2
  - r-progress=1.2.3
  - libegl=1.7.0
  - r-polynom=1.4_1
  - r-progressr=0.15.1
  - r-metbrewer=0.2.0
  - r-pbkrtest=0.5.5
  - requests==2.32.5
  - r-pbdzmq=0.3_14
  - matplotlib==3.10.8
  - r-listenv=0.9.1
  - _r-mutex=1.0.1
  - r-rcpp=1.1.0
  - hyperframe=6.1.0
  - sed=4.9
  - six=1.17.0
  - r-cellranger=1.1.0
  - libopenblas=0.3.30
  - r-foreach=1.5.2
  - r-memoise=2.0.1
  - xcb-util-image=0.4.0
  - typing_extensions==4.15.0
  - r-quantreg=6.1
  - font-ttf-source-code-pro=2.038
  - bioconductor-s4arrays=1.2.0
  - h11=0.16.0
  - bleach-with-css==6.3.0
  - r-gtable=0.3.6
  - r-crayon=1.5.3
  - r-cardata=3.0_5
  - r-future==1.67.0
  - libfreetype6==2.14.1
  - curl==8.17.0
  - r-stringr==1.5.2
  - libxslt=1.1.43
  - r-car=3.1_3
  - r-minqa=1.2.8
  - r-ipred=0.9_15
  - psutil==7.2.1
  - lerc=4.0.0
  - cached_property=1.5.2
  - libglx=1.7.0
  - r-cli=3.6.5
  - fonts-conda-forge=1
  - nbconvert-core=7.16.6
  - r-dtplyr==1.3.2
  - r-farver=2.1.2
  - r-curl==7.0.0
  - cairo=1.18.4
  - idna==3.11
  - xorg-libxext=1.3.6
  - libffi==3.5.2
  - r-lubridate=1.9.4
  - r-crosstalk==1.2.2
  - bioconductor-interactivedisplaybase=1.40.0
  - typing-extensions==4.15.0
  - r-caret=6.0_94
  - r-cachem=1.1.0
  - r-bitops=1.0_9
  - xorg-libxxf86vm=1.1.6
  - r-fansi=1.0.6
  - contourpy=1.3.2
  - bioconductor-keggrest=1.42.0
  - r-ps=1.9.1
  - openjpeg==2.5.4
  - wcwidth==0.2.14
  - libgfortran==15.2.0
  - threadpoolctl=3.6.0
  - hpack=4.1.0
  - r-viridislite=0.4.2
  - r-matrixstats=1.5.0
  - r-parallelly==1.45.1
  - r-rmarkdown=2.29
  - fontconfig=2.15.0
  - rfc3339-validator=0.1.4
  - async-lru=2.0.5
  - make=4.4.1
  - libuuid==2.41.3
  - libgl=1.7.0
  - r-fastmap=1.2.0
  - r-reformulas=0.4.1
  - r-withr=3.0.2
  - r-rcurl==1.98_1.17
  - r-nloptr==2.0.3
  - bioconductor-hipathia=3.2.0
  - r-mime=0.13
  - gfortran_impl_linux-64==15.2.0
  - munkres=1.1.4
  - stack_data=0.6.3
  - _openmp_mutex=4.5
  - r-recipes=1.3.1
  - r-mvtnorm=1.3_3
  - r-futile.options=1.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - unicodedata2==17.0.0
  - r-openssl=2.3.3
  - kernel-headers_linux-64==6.12.0
  - r-rematch2=2.1.2
  - webencodings=0.5.1
  - gmp=6.3.0
  - r-haven==2.5.5
  - sniffio=1.3.1
  - _libgcc_mutex=0.1
  - tomli==2.3.0
  - bioconductor-biocparallel=1.36.0
  - jinja2=3.1.6
  - r-globals=0.18.0
  - libntlm=1.8
  - jupyterlab==4.5.1
  - r-conquer=1.3.3
  - r-servr=0.32
  - r-nnet=7.3_20
  - r-survival=3.8_3
  - notebook-shim=0.2.4
  - jsonschema-specifications==2025.9.1
  - r-rsqlite==2.4.3
  - bioconductor-s4vectors=0.40.2
  - libgcc-devel_linux-64==15.2.0
  - openldap=2.6.10
  - font-ttf-ubuntu=0.83
  - jsonpointer=3.0.0
  - patsy==1.0.2
  - jupyter_server_terminals=0.5.3
  - r-jsonlite=2.0.0
  - libjpeg-turbo==3.1.2
  - pyyaml==6.0.3
  - r-yaml=2.3.10
  - bioconductor-preprocesscore=1.64.0
  - zstandard==0.25.0
  - pango=1.56.4
  - r-mgcv=1.9_3
  - bioconductor-delayedarray=0.28.0
  - pyside6==6.9.2
  - r-futile.logger=1.4.3
  - mistune==3.2.0
  - bioconductor-matrixgenerics=1.14.0
  - r-bit64=4.6.0_1
  - r-formula=1.2_5
  - soupsieve==2.8.1
  - libstdcxx==15.2.0
  - r-proc==1.19.0.1
  - r-plogr=0.2.0
  - libxcrypt=4.4.36
  - xcb-util=0.4.1
  - libpq==17.7
  - decorator=5.2.1
  - r-uuid=1.2_1
  - r-tibble=3.3.0
  - joblib==1.5.3
  - libgcc-ng==15.2.0
prefix: /home/ags/miniconda3/envs/UPO_TFM
